/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":jdbc"))
    implementation(project(":jpa"))
    implementation(project(":model"))
    implementation(project(":repositories"))

    implementation("com.github.freva:ascii-table:1.8.0")
    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation("org.slf4j:slf4j-simple:1.7.36")
}

application {
    // Define the main class for the application.
    mainClass = "cat.uvic.teknos.miruvic.ui.App"
}