/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
    id("application")
}

application {
    // Replace with your actual main class
    mainClass.set("cat.uvic.teknos.dam.miruvic.server.App")
}

dependencies {
    implementation(project(":utils"))
    implementation(project(":jdbc"))
    implementation(project(":jpa"))
    implementation(project(":model"))
    implementation(project(":repositories"))

    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.17.2")
    implementation("com.mysql:mysql-connector-j:9.3.0")
    implementation("com.athaydes.rawhttp:rawhttp-core:2.6.0")
    implementation("com.fasterxml.jackson.core:jackson-core:2.17.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.17.2")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2")
    implementation("org.slf4j:slf4j-simple:1.7.36")
    testImplementation("org.mockito:mockito-core:5.11.0")
}